---
title: "Budapest Pizza Report"
author: "KFC Team"
date: '2020 10 14 '
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Intoduction
  The purpose of the report is to explore data about pizza prices in Budapest. [GitHub](https://github.com/cosmin-ticu/Data_ExercisesANDhomework_DA1/tree/master/Task1_KFC_Team)
  
```{r , include = FALSE}
library(tidyverse)
library(readxl)
data_in <- "C:/Users/acer/Desktop/OneDrive - Central European University/Courses/Fall_Term/Coding_1/data/Pizza"
pizza_data <- read_excel( paste0(data_in,"/raw/KFC-team_pizza_data.xlsx") )
```

## Summary

```{r, }
summary(pizza_data$price_pizza)
```

## Plots
```{r, }
ggplot( data = pizza_data , aes( x = price_pizza ) ) +
  geom_histogram( aes(y = ..density..) , fill = 'navyblue' , binwidth = 15 ) +
  geom_density( aes(y = ..density..) , fill = 'red' , bw = 15, alpha = 0.5 ) +
  labs(x='Price of Margherita Pizza in Budapest',y='Density')+
  scale_y_continuous(labels = scales::percent)
```

## Tables
```{r, }
library(moments)
pizza_stat <- pizza_data %>% summarise(
  mean     = mean(price_pizza),
  median   = median(price_pizza),
  std      = sd(price_pizza),
  iq_range = IQR(price_pizza), 
  min      = min(price_pizza),
  max      = max(price_pizza),
  skew     = skewness(price_pizza),
  numObs   = n() )
knitr::kable(pizza_stat,caption="Summary stat for hotel prices")
```

Better table
```{r, results = "asis", warning = FALSE, message = FALSE }
library(xtable)

xtb <- xtable(pizza_stat, type = "latex", caption = "Summary statistics - elegant package")
print(xtb, comment=FALSE, include.rownames=FALSE)
```

## Summary of results

